services:
  - type: web
    name: la-verdad-herald-backend
    env: php
    region: oregon
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    rootDir: backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:IF+Rt6jGkdsxWN4y7WXBUVZ08SZByr+E3sYClY7cG+8=
      - key: APP_DEBUG
        value: false