services:
  - type: web
    name: la-verdad-herald-backend
    env: php
    region: oregon
    plan: free
    buildCommand: cd backend && composer install --no-dev --optimize-autoloader
    startCommand: cd backend && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:IF+Rt6jGkdsxWN4y7WXBUVZ08SZByr+E3sYClY7cG+8=
      - key: APP_DEBUG
        value: false